- name: Install deps
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Add google public signing key to keyring
  ansible.builtin.shell: |
    curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg


- name: Add google repo to source lists
  ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Install kubeadm, kubectl, kubelet
  ansible.builtin.apt:
    pkg:
      - kubeadm
      - kubectl
      - kubelet
    state: present
    update_cache: yes


- name: Enable kubelet service
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: yes
